# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b1dccc1232c7ab16019a33d6f12a99fbf1e14df8c1da74c7a4b888401fe55c370ef0dca8b663a8ba9c2b81572df098c28a5009e63612f7fb285ed66d13030a76

test:
  secret_key_base: e61ad62196d65235a9830509e796fe8540a539e6d325f6dcf6eba1139e66ae232abe54c038191c41501d060444365b80249f890418b3cf656ebd83d5eec6e3de

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
